import React, { useState, useRef } from 'react';
import { AIDoctorLogoIcon, DownloadIcon, CloseIcon, EyeIcon, BackIcon } from './icons';
import { PatientInfo } from '../types';

// Inform TypeScript that html2canvas is globally available from the CDN script
declare const html2canvas: any;

interface PrescriptionProps {
  patientInfo: PatientInfo;
  illnessTitle: string;
  content: string;
  advice: string;
  onReset: () => void;
  onEdit: () => void;
}

const RTL_LANGUAGES = ['Arabic', 'Urdu'];

const parseContent = (text: string, language: string, isPreview?: boolean) => {
  const sections = text.split(/(?=## )/).filter(s => s.trim() !== '');

  return sections.map((section, index) => {
    const lines = section.split('\n');
    const title = lines[0].replace('## ', '').trim();
    const contentLines = lines.slice(1).filter(line => line.trim() !== '');
    
    const isRtl = RTL_LANGUAGES.includes(language);
    // The 'font-urdu' class is specifically for Noto Nastaliq Urdu. We should only apply it for Urdu.
    const isUrduFontNeeded = language === 'Urdu';
    
    // Force light theme styles in preview for a clean, paper-like download
    const wrapperClasses = isPreview 
      ? `bg-white rounded-xl shadow-lg p-6 mb-6 break-inside-avoid ${isUrduFontNeeded ? 'font-urdu' : ''}`
      : `bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 mb-6 break-inside-avoid print:shadow-none print:border print:border-gray-300 ${isUrduFontNeeded ? 'font-urdu' : ''}`;
    const titleClasses = isPreview
      ? `text-2xl font-bold text-teal-600 mb-4 border-b-2 border-gray-200 pb-3`
      : `text-2xl font-bold text-teal-600 dark:text-teal-400 mb-4 border-b-2 border-gray-200 dark:border-gray-700 pb-3 print:border-gray-600`;
    const listClasses = isPreview
      ? `list-disc space-y-2 text-gray-700 ${isRtl ? 'pr-5' : 'pl-5'}`
      : `list-disc space-y-2 text-gray-700 dark:text-gray-300 ${isRtl ? 'pr-5' : 'pl-5'}`;

    return (
      <div key={index} className={wrapperClasses} dir={isRtl ? 'rtl' : 'ltr'}>
        <h2 className={titleClasses}>{title}</h2>
        <div className="space-y-2">
            <ul className={listClasses}>
                {contentLines.map((line, i) => (
                    <li key={i}>{line.replace(/[\*\-]\s*/, '')}</li>
                ))}
            </ul>
        </div>
      </div>
    );
  });
};

const Disclaimer = ({ isPreview }: { isPreview?: boolean }) => (
    <div className={`mt-8 pt-4 border-t-2 ${isPreview ? 'border-gray-300' : 'border-gray-300 dark:border-gray-600'} text-center`}>
        <p className={`text-xs ${isPreview ? 'text-gray-500' : 'text-gray-500 dark:text-gray-400'} italic`}>
            <strong>Disclaimer:</strong> This prescription is generated by an AI model. It is intended for informational purposes only and should not be considered a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider before making any health decisions or starting any new treatment.
        </p>
    </div>
);

const PrescriptionBody = React.forwardRef<HTMLDivElement, { content: string; advice: string; patientInfo: PatientInfo; illnessTitle: string; isPreview?: boolean }>(({ content, advice, patientInfo, illnessTitle, isPreview }, ref) => {
    const { language } = patientInfo;
    return (
        <div ref={ref} className={`print-area p-4 sm:p-6 ${isPreview ? 'bg-white text-gray-800' : 'bg-transparent text-black'}`}>
            <div className="hidden print:block mb-8">
                <div className={`flex items-center justify-between border-b-2 pb-4 ${isPreview ? 'border-gray-800' : 'border-gray-800 dark:border-gray-600'}`}>
                    <div className="flex items-center space-x-3">
                        <AIDoctorLogoIcon className="h-12 w-12 text-teal-600" />
                        <div>
                            <h1 className={`text-3xl font-bold ${isPreview ? 'text-gray-800' : 'text-gray-800 dark:text-white'}`}>AI Doctor</h1>
                            <p className={isPreview ? 'text-gray-600' : 'text-gray-600 dark:text-gray-400'}>Your Personal Health Advisor</p>
                        </div>
                    </div>
                    <p className={`text-sm ${isPreview ? 'text-gray-500' : 'text-gray-500 dark:text-gray-300'}`}>Date: {new Date().toLocaleDateString()}</p>
                </div>
            </div>
            
            {/* Patient Info Header */}
            <div className={`mb-8 p-4 rounded-lg ${isPreview ? 'bg-gray-50' : 'bg-gray-50 dark:bg-gray-900/50'} border ${isPreview ? 'border-gray-200' : 'border-gray-200 dark:border-gray-700'}`}>
                <div className="flex justify-between items-start">
                    <div>
                        <h2 className={`text-2xl font-bold ${isPreview ? 'text-gray-900' : 'text-gray-900 dark:text-white'} whitespace-nowrap`}>{patientInfo.name}</h2>
                        <p className={`text-sm ${isPreview ? 'text-gray-600' : 'text-gray-600 dark:text-gray-400'} mt-1`}>
                            Age: {patientInfo.age} | District: {patientInfo.district} {patientInfo.cell && `| Cell: ${patientInfo.cell}`}
                        </p>
                    </div>
                    <div className="text-right flex-shrink-0 ml-4">
                         <p className={`text-sm font-semibold ${isPreview ? 'text-gray-700' : 'text-gray-700 dark:text-gray-300'}`}>Condition</p>
                         <p className={`text-md font-medium ${isPreview ? 'text-teal-600' : 'text-teal-600 dark:text-teal-400'}`}>{illnessTitle}</p>
                    </div>
                </div>
            </div>
            
            {parseContent(content, language, isPreview)}
            {advice && parseContent(advice, language, isPreview)}
            <Disclaimer isPreview={isPreview} />
        </div>
    );
});


export const Prescription: React.FC<PrescriptionProps> = ({ content, advice, patientInfo, illnessTitle, onReset, onEdit }) => {
  const [isPreviewing, setIsPreviewing] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    const element = previewRef.current;
    if (!element || typeof html2canvas === 'undefined') {
      console.error("Preview element not found or html2canvas library is not available.");
      return;
    }

    try {
        const canvas = await html2canvas(element, {
            scale: 2, // Higher resolution for better quality
            useCORS: true,
            backgroundColor: '#ffffff', // Force a white background for the output image
        });
        
        const link = document.createElement('a');
        link.href = canvas.toDataURL('image/png');
        link.download = `prescription-${patientInfo.name.replace(/\s/g, '_')}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (error) {
        console.error("Error generating prescription image:", error);
    }
  };

  if (isPreviewing) {
    return (
      <div className="fixed inset-0 bg-gray-200 dark:bg-gray-900 z-50 overflow-y-auto no-print">
        <header className="sticky top-0 bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm z-10 p-4 shadow-md flex justify-between items-center">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">Prescription Preview</h2>
          <div className="flex items-center gap-4">
            <button onClick={handleDownload} className="flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-transform transform hover:scale-105">
              <DownloadIcon className="w-5 h-5" /> Download
            </button>
            <button onClick={() => setIsPreviewing(false)} className="p-2 rounded-full bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 hover:bg-gray-300 dark:hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500">
               <CloseIcon className="w-6 h-6" />
            </button>
          </div>
        </header>
        <main className="p-4 sm:p-8">
          <div className="max-w-4xl mx-auto bg-white shadow-2xl">
            <PrescriptionBody content={content} advice={advice} patientInfo={patientInfo} illnessTitle={illnessTitle} ref={previewRef} isPreview={true} />
          </div>
        </main>
      </div>
    );
  }

  return (
    <div id="printable-content-wrapper" className="w-full max-w-4xl mx-auto">
      <div id="printable-content" className="print-area print:text-black">
        <PrescriptionBody content={content} advice={advice} patientInfo={patientInfo} illnessTitle={illnessTitle} />
      </div>
      <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4 no-print">
         <button
          onClick={onEdit}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-gray-600 text-white font-semibold rounded-lg shadow-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-transform transform hover:scale-105"
        >
          <BackIcon className="w-5 h-5" />
          Go Back & Edit
        </button>
        <button
          onClick={() => setIsPreviewing(true)}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 bg-teal-600 text-white font-semibold rounded-lg shadow-md hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2 transition-transform transform hover:scale-105"
        >
          <EyeIcon className="w-5 h-5" />
          Preview Prescription
        </button>
        <button
          onClick={onReset}
          className="w-full sm:w-auto px-6 py-3 bg-red-600 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition-transform transform hover:scale-105"
        >
          Start New
        </button>
      </div>
    </div>
  );
};